// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BackTestListItemController from "./back_test_list_item_controller"
import OptionGroupController from "./option_group_controller"
import SliderController from "./slider_controller"
import IncrementorController from "./incrementor_controller"
import RadioGroupController from "./radio_group_controller"

application.register("back-test-list-item", BackTestListItemController)
application.register("option-group", OptionGroupController)
application.register("slider", SliderController)
application.register("incrementor", IncrementorController)
application.register("radio-group", RadioGroupController)
